### ISSUE TITLE
Simplify current Trilinos patch

### ISSUE THREAD

**Issue by davydden** [koecher/candi#16]
...by `-DHAVE_SUPERLUDIST_LUSTRUCTINIT_2ARG:BOOL=ON`

**Comment by koecher** [comment]
Good point, I'll test this out next week. Thx a lot.
May you be so kind and set up a pull request for the changed trilions.package configuration?

**Comment by davydden** [comment]
I am sorry, but i don't use candi and I am not familiar with it at all. I just gave a brief look at the way Trilinos is installed here.

**Comment by koecher** [comment]
Done. Thank you again for pointing that solution out.

**Comment by davydden** [comment]
you are welcome!
