### ISSUE TITLE
dealii can't find PETSC

### ISSUE THREAD

**Issue by davydden** [koecher/candi#28]
subj. installing with `./candi.sh deal.II/platforms/supported/linux_cluster.platform`.

```
-- Include /home/woody/iwtm/iwtm108/.candi/apps/unpack/deal.II-v8.3.0/cmake/configure/configure_3_petsc.cmake
-- PETSC_LIBRARY not found! Call:
--     FIND_LIBRARY(PETSC_LIBRARY NAMES petsc HINTS /home/woody/iwtm/iwtm108/.candi/apps/deal.II/default-default/petsc-3.6.1 /home/woody/iwtm/iwtm108/.candi/apps/deal.II/default-default/petsc-3.6.1/ PATH_SUFFIXES lib lib64 lib)
-- PETSC_INCLUDE_DIR_ARCH not found! Call:
--     FIND_PATH(PETSC_INCLUDE_DIR_ARCH petscconf.h HINTS /home/woody/iwtm/iwtm108/.candi/apps/deal.II/default-default/petsc-3.6.1 /home/woody/iwtm/iwtm108/.candi/apps/deal.II/default-default/petsc-3.6.1/ PATH_SUFFIXES petsc include include/petsc)
-- PETSC_INCLUDE_DIR_COMMON not found! Call:
--     FIND_PATH(PETSC_INCLUDE_DIR_COMMON petscversion.h HINTS /home/woody/iwtm/iwtm108/.candi/apps/deal.II/default-default/petsc-3.6.1 /home/woody/iwtm/iwtm108/.candi/apps/deal.II/default-default/petsc-3.6.1/ PATH_SUFFIXES petsc include include/petsc)
-- PETSC_PETSCVARIABLES not found! Call:
--     FIND_FILE(PETSC_PETSCVARIABLES NAMES petscvariables HINTS /home/woody/iwtm/iwtm108/.candi/apps/deal.II/default-default/petsc-3.6.1/ /home/woody/iwtm/iwtm108/.candi/apps/deal.II/default-default/petsc-3.6.1 PATH_SUFFIXES conf)
--   PETSC_LIBRARIES: *** Required variable "PETSC_LIBRARY" set to NOTFOUND ***
--   PETSC_INCLUDE_DIRS: *** Required variable "PETSC_INCLUDE_DIR_COMMON" set to NOTFOUND ***
--   PETSC_USER_INCLUDE_DIRS: *** Required variable "PETSC_INCLUDE_DIR_COMMON" set to NOTFOUND ***
-- Could NOT find PETSC
-- DEAL_II_WITH_PETSC has unmet external dependencies.
```

don't know how to debug it as cmake command is not displayed, but PETSc and SLEPc are installed via candi fine. Supposedly has to do with
```
CONFOPTS="${CONFOPTS} \
-D PETSC_DIR=${PETSC_DIR} \
"

CONFOPTS="${CONFOPTS} \
-D SLEPC_DIR=${SLEPC_DIR} \
"
```

**Comment by koecher** [comment]
Hmpf, the path hint (given by deal.II) looks fine:
"petsc HINTS /home/woody/iwtm/iwtm108/.candi/apps/deal.II/default-default/petsc-3.6.1"
may you check, if petsc is correctly installed there?

Otherwise, you can debug a little with scripting, like:
echo ${CONFOPTS}
CONFOPTS="${CONFOPTS} \
-D PETSC_DIR=${PETSC_DIR} \
"
echo ${CONFOPTS}

This should output the confopts variable before and after the modification.

**Comment by davydden** [comment]
it seems there are several issues: 
1. PETSc dir is empty.
2. inside `default-default` there are only `petsc-3.6.1` (empty) and `p4est.git`. Everything else seems to be installed in `default-default`, i.e. I have `default-default/lib` with whole bunch of Trilinos libraries, hdf5, etc

**Comment by koecher** [comment]
Okay, then the installation of petsc was unsuccessful. Please remove the build folder of petsc and let it run again.
The other things noted in 2. are correct. p4est and petsc are a bit complicated and non-standard such that they have their own subfolder within the final installation.

**Comment by davydden** [comment]
i see, will try to re-do it now...

**Comment by davydden** [comment]
same issue, petsc folder is empty...

**Comment by davydden** [comment]
`UNABLE to CONFIGURE with GIVEN OPTIONS` in `configure.log` of petsc.

**Comment by davydden** [comment]
```
Could not find a functional BLAS. Run with --with-blas-lib=<lib> to indicate the library containing BLAS.
 Or --download-fblaslapack=1 to have one automatically downloaded and installed
```

it seems that mechanics of providing blas to PETSc is missing. As a quick work-around there must be something like:
```
IF MKL==ON
    --with-blas-lapack-lib=/path/to/mkl/libmkl1.so;/path/to/mkl/libmkl2.so
END
```
or
```
--with-blas-lapack-dir=/path/to/mkl/
```

**Comment by koecher** [comment]
@Rombur can you test the approach of @davydden ?

**Comment by tjhei** [comment]
Do you have #25 in your version already? That should fix the problem that candi thinks everything is fine even though petsc installation failed.

**Comment by davydden** [comment]
i am on a8c00759a105890703eed745deadb9b21ab137b2 so no, it's a couple of commits behind.

**Comment by davydden** [comment]
but as I wrote, i think it's an issue of blas detection by petsc. As far as I can tell, the bash script has to be modified to be more flexible to different building environment.

**Comment by koecher** [comment]
In the branch release_preparings_v0.6 I've added the two variables:
# BLAS_DIR=
# LAPACK_DIR=
For setting the blas and lapack dirs. When you set them, does petsc automatically use your lapack/blas? Sry, I have no machine which is similar to yours to test this.

**Comment by davydden** [comment]
i do have `BLAS_DIR ` and `LAPACK_DIR ` set to `${MKLROOT}/lib/intel64` but `petsc.package`, as of commit referenced above, does not use those variables. 

Let me know when you merge https://github.com/koecher/candi/pull/31 and I will give it a fresh start.

**Comment by Rombur** [comment]
Darn, I never use petsc so I guess I forgot to check that MKL works with petsc. I will look into it.

**Comment by koecher** [comment]
Okay, then I understand what possibly can be done regarding your issue.

The PR #31 is merged into the branch "release_preparings_v0.6" (git checkout release_preparings_v0.6)

I have pushed a patch for your problem into that branch for testing issues.
There is some more work to do until v0.6 is ready to be shipped.

**Comment by Rombur** [comment]
This branch breaks trilinos for me. I am busy this morning but I will look
into it this afternoon.

**Comment by Rombur** [comment]
Well I don't know what happened, I had this weird bug but now it works... I can't compile petsc with MKL though. The compilation crashes with a strange bug in mpi. I guess that petsc has some problem with Intel mpi. Since it's the only cluster where I have access to MKL, I won't be able to check that MKL and PETSc work together.

**Comment by koecher** [comment]
Okay, thx a lot.
@davydden may you check if this branch is working for your mpi/MKL/petsc?
Otherwise I only see the option of disabling petsc, if MKL is set to on.

**Comment by davydden** [comment]
Will do tomorrow...

**Comment by davydden** [comment]
this 7a28523608b5804c3bb3180b5c32a8b37c6d50de worked.
