### ISSUE TITLE
cecho may be called before definition

### ISSUE THREAD

**Issue by xywei** [koecher/candi#54]
At line 92, cecho is called if neither wget nor curl is installed, which is ahead of its definition. This can produce confusing error messages, since there is another "cecho" program for windows.

**Comment by koecher** [comment]
Thank you for this info. Windows is currently not really supported, but I'll look at the code.

**Comment by koecher** [comment]
You are right, also the variable BAD is not defined at this stage.
May you please set up a pull request, where you change line 92 from
`cecho ${BAD} "Please install wget or curl."`
to
`echo "Please install wget or curl."`

**Comment by xywei** [comment]
Done as you suggested :D.

**Comment by koecher** [comment]
Done by PR #55
