### ISSUE TITLE
Cluster

### ISSUE THREAD

**Issue by ESeNonFossiIo** [koecher/candi#73]
I got some problem with `candi` on a cluster: on the login node I can not compile but on compute node I can not download anything.
Is there a way to set candi to just dowloand or to just compile?

P.S.:
I like very much `candi`! Thank you!

**Comment by koecher** [comment]
Yes it is. Run candi on a other machine such that the download folder is complete. Then copy the source dir and for deal.II also the unpack/deal.II dir onto your shared space. Then candi will see the downloads and do not try to download them.
To just compile (everything downloaded and unpacked) you can set the DEVELOPER_MODE=ON switch in the candi.cfg file. (but make sure that you have copied the unpack folder completely.
Hope that helps you out.

**Comment by ESeNonFossiIo** [comment]
Ok. Thanks! I will try. Btw, I think that flags like `./candi --only-download` or `./candi --only-compile` would be a very nice feature for clusters.
Thank you again for you answer! :)

**Comment by koecher** [comment]
I thought about something like this. We are currently staging candi as installer for deal.II
Afterwards I will throw a discussion about this point.
Kind regards Uwe
