### ISSUE TITLE
MPI config?

### ISSUE THREAD

**Issue by yiyangzhang37** [koecher/candi#77]
Hello guys!

I was told that this is a easy installer of dealii... I went through the config file, MPI wasn't mentioned.. May I ask if it sets MPI = ON by default?

Thank you!

**Comment by tjhei** [comment]
The correct repo to look at is https://github.com/dealii/candi not this one.

> May I ask if it sets MPI = ON by default?

Yes, in fact we currently only support MPI = ON right now.

**Comment by koecher** [comment]
@jtceleron MPI is the default, you do not have to do anything. When you start candi, you see that mpi compilers are needed.

@tjhei yes, but I keep this repo in sync
