### ISSUE TITLE
Zoltan2 requires ParMETIS_version 4.0.3

### ISSUE THREAD

**Issue by mgouiza** [koecher/candi#79]
Hi All,

I am having an issue with ParaMETIS, when candi tries to build trilinos 12-10-1?

I get this error:

```
CMake Error at packages/zoltan2/CMakeLists.txt:8 (MESSAGE):
  Zoltan2 requires ParMETIS_version 4.0.3 or later.  Upgrade or set
  TPL_ENABLE_ParMETIS OFF or set Zoltan2_ENABLE_ParMETIS OFF.
-- Configuring incomplete, errors occurred!
See also "/home/ufaserv1_k/earmgo/bin/tmp/build/trilinos-release-12-10-1/CMakeFiles/CMakeOutput.log".
Failure with exit status: 1
Exit message: There was a problem configuring trilinos 12-10-1.
```

Although ParMETIS_version 4.0.3 was successfully installed by candi

Thank you for your help

**Comment by koecher** [comment]
* On which platform you are trying to install?
* Is it by chance possible, that you have another parmetis or metis version installed in your system?

**Comment by koecher** [comment]
Also, look at line 109 in the trilinos package file
https://github.com/dealii/candi/blob/master/deal.II-toolchain/packages/trilinos.package

Seems that we had a similar problem before.

**Comment by mgouiza** [comment]
Hi Koecher,

-platform: CentOS 7
-no other parmetis/metis intallation.

I did the  #  -D HAVE_PARMETIS_VERSION_4_0_3=ON" which solved the initial problem, but then ran into other problems. So I decided to install deal.II without candi. It was time consuming but worked.
Thanks for your help.

**Comment by koecher** [comment]
the issue will be resolved by
https://github.com/dealii/candi/pull/85
