### ISSUE TITLE
Status of Download Mirrors

### ISSUE THREAD

**Issue by stmcgovern** [koecher/candi#83]
Hi Uwe and Timo, 
I am trying to reinstall dealii with candi (from master), and I don't seem to be able to get the fetching from the servers to work out for the various dependencies (timeout). I'm curious if this is just me or if you are redoing some infrastructure with the links? 

Thanks, 
Sean

**Comment by tjhei** [comment]
Things are working for me. Are you using https://github.com/dealii/candi (this repo here is not up to date)?

**Comment by stmcgovern** [comment]
I replied directly to the email, so this might be redundant:
-----
candi tries now to download, configure, build and install:

Project:  deal.II-toolchain
Platform: deal.II-toolchain/platforms/supported/fedora28.platform

Loading dealii-prepare
Fetching p4est 2.2
Trying to download https://tjhei.info/candi-mirror/p4est-2.2.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time Time  Current
                                 Dload  Upload   Total   Spent Left  Speed
100   340  100   340    0     0    724      0 --:--:-- --:--:-- --:--:--   724
  0     0    0     0    0     0      0      0 --:--:--  0:00:41 --:--:--     0
curl: (22) The requested URL returned error: 403 Forbidden
Trying to download https://cecas.clemson.edu/dealii/mirror/p4est-2.2.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time Time  Current
                                 Dload  Upload   Total   Spent Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 403 Forbidden
Trying to download https://p4est.github.io/release/p4est-2.2.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time Time  Current
                                 Dload  Upload   Total   Spent Left  Speed
100 2566k  100 2566k    0     0  5013k      0 --:--:-- --:--:-- --:--:-- 5003k
Verifying p4est-2.2.tar.gz
p4est-2.2.tar.gz: OK
Unpacking p4est-2.2.tar.gz
Building p4est 2.2
CFLAGS_FAST: -O2
CFLAGS_DEBUG: -O0 -g

This script tries configure and build the p4est library.
Build FAST: /user/smcgover/home/Develop/deal.ii-candi/tmp/build/p4est-2.2/FAST
Build DEBUG: /user/smcgover/home/Develop/deal.ii-candi/tmp/build/p4est-2.2/DEBUG
Install FAST: /user/smcgover/home/Develop/deal.ii-candi/p4est-2.2/FAST
Install DEBUG: /user/smcgover/home/Develop/deal.ii-candi/p4est-2.2/DEBUG
Checking environment: CFLAGS P4EST_CFLAGS_FAST P4EST_CFLAGS_DEBUG
See output in files .../config.output and .../make.output

Build FAST version in /user/smcgover/home/Develop/deal.ii-candi/tmp/build/p4est-2.2/FAST
libtool: warning: relinking 'src/libp4est.la'
FAST version installed in /user/smcgover/home/Develop/deal.ii-candi/p4est-2.2/FAST

Build DEBUG version in /user/smcgover/home/Develop/deal.ii-candi/tmp/build/p4est-2.2/DEBUG
libtool: warning: relinking 'src/libp4est.la'
DEBUG version installed in /user/smcgover/home/Develop/deal.ii-candi/p4est-2.2/DEBUG

Fetching trilinos 12-10-1
Trying to download https://tjhei.info/candi-mirror/trilinos-release-12-10-1.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time Time  Current
                                 Dload  Upload   Total   Spent Left  Speed
100   355  100   355    0     0    841      0 --:--:-- --:--:-- --:--:--   839
  0     0    0     0    0     0      0      0 --:--:--  0:02:09 --:--:--     0
curl: (7) Failed to connect to cecas.clemson.edu port 443: Connection timed out
Trying to download https://cecas.clemson.edu/dealii/mirror/trilinos-release-12-10-1.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time Time  Current
                                 Dload  Upload   Total   Spent Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:23 --:--:--     0
curl: (22) The requested URL returned error: 403 Forbidden
Trying to download https://github.com/trilinos/Trilinos/archive/trilinos-release-12-10-1.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time Time  Current
                                 Dload  Upload   Total   Spent Left  Speed
100   143    0   143    0     0    521      0 --:--:-- --:--:-- --:--:--   523
100  112M    0  112M    0     0  5854k      0 --:--:--  0:00:19 --:--:-- 5699k
Verifying trilinos-release-12-10-1.tar.gz
trilinos-release-12-10-1.tar.gz: FAILED
md5sum: WARNING: 1 computed checksum did NOT match
Verifying trilinos-release-12-10-1.tar.gz
trilinos-release-12-10-1.tar.gz: FAILED
md5sum: WARNING: 1 computed checksum did NOT match
trilinos-release-12-10-1.tar.gz in your download folder is corrupted
Corrupted trilinos-release-12-10-1.tar.gz has been removed!
Trying to download https://tjhei.info/candi-mirror/trilinos-release-12-10-1.tar.gz
--2019-12-17 12:55:51-- https://tjhei.info/candi-mirror/trilinos-release-12-10-1.tar.gz
Resolving tjhei.info (tjhei.info)... 45.63.8.119
Connecting to tjhei.info (tjhei.info)|45.63.8.119|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://cecas.clemson.edu/dealii/mirror/trilinos-release-12-10-1.tar.gz [following]
--2019-12-17 12:55:51-- https://cecas.clemson.edu/dealii/mirror/trilinos-release-12-10-1.tar.gz
Resolving cecas.clemson.edu (cecas.clemson.edu)... 130.127.200.74
Connecting to cecas.clemson.edu (cecas.clemson.edu)|130.127.200.74|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2019-12-17 12:55:52 ERROR 403: Forbidden.

Trying to download https://cecas.clemson.edu/dealii/mirror/trilinos-release-12-10-1.tar.gz
--2019-12-17 12:55:52-- https://cecas.clemson.edu/dealii/mirror/trilinos-release-12-10-1.tar.gz
Resolving cecas.clemson.edu (cecas.clemson.edu)... 130.127.200.74
Connecting to cecas.clemson.edu (cecas.clemson.edu)|130.127.200.74|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2019-12-17 12:55:52 ERROR 403: Forbidden.

Trying to download https://github.com/trilinos/Trilinos/archive/trilinos-release-12-10-1.tar.gz
--2019-12-17 12:55:52-- https://github.com/trilinos/Trilinos/archive/trilinos-release-12-10-1.tar.gz
Resolving github.com (github.com)... 140.82.118.3
Connecting to github.com (github.com)|140.82.118.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/trilinos/Trilinos/tar.gz/trilinos-release-12-10-1 [following]
--2019-12-17 12:55:53-- https://codeload.github.com/trilinos/Trilinos/tar.gz/trilinos-release-12-10-1
Resolving codeload.github.com (codeload.github.com)... 192.30.253.120
Connecting to codeload.github.com (codeload.github.com)|192.30.253.120|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘trilinos-release-12-10-1.tar.gz’

trilinos-release-12-10-1.tar.gz [ <=>                   ] 112.19M  3.55MB/s    in 21s

2019-12-17 12:56:15 (5.30 MB/s) - ‘trilinos-release-12-10-1.tar.gz’ saved [117638754]

Verifying trilinos-release-12-10-1.tar.gz
trilinos-release-12-10-1.tar.gz: FAILED
md5sum: WARNING: 1 computed checksum did NOT match
Verifying trilinos-release-12-10-1.tar.gz
trilinos-release-12-10-1.tar.gz: FAILED
md5sum: WARNING: 1 computed checksum did NOT match
Failure with exit status: 3
Exit message: Error verifying checksum for trilinos-release-12-10-1.tar.gz
Make sure that you are connected to the internet.
[smcgover@yirgacheffe candi]$

**Comment by koecher** [comment]
Hei. As Timo has it already written. I did not update this repo here. Should be fine if you clone it from dealii/candi

**Comment by koecher** [comment]
otherwise please write an issue there.

**Comment by stmcgovern** [comment]
Ok. That log is from the dealii/candi and I'll pursue the issue over there. Thanks, Sean
-------- Original message --------From: Uwe Köcher <notifications@github.com> Date: 17/12/2019  17:03  (GMT+01:00) To: koecher/candi <candi@noreply.github.com> Cc: stmcgovern <st.mcgovern@gmail.com>, Author <author@noreply.github.com> Subject: Re: [koecher/candi] Status of Download Mirrors (#83) otherwise please write an issue there.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/koecher/candi/issues/83?email_source=notifications\u0026email_token=AAYC46V75UF2GXWYOQPYCSTQZDZ5TA5CNFSM4J3N4LGKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHC44BQ#issuecomment-566611462",
"url": "https://github.com/koecher/candi/issues/83?email_source=notifications\u0026email_token=AAYC46V75UF2GXWYOQPYCSTQZDZ5TA5CNFSM4J3N4LGKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHC44BQ#issuecomment-566611462",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by tjhei** [comment]
@stmcgovern thanks for the error. It looks like there are two problems going on at the same time that you are encountering: https://github.com/dealii/candi/issues/125 https://github.com/dealii/candi/issues/126

 You can try commenting/deleting the line "CHECKSUM=40f28628b63310f9bd17c26d9ebe32b1" in the file packages/trilinos.package to get it to install right now.

**Comment by koecher** [comment]
instead of deleting the checksum line, please use
```CHECKSUM=ignore```

**Comment by stmcgovern** [comment]
OK. That makes sense. Thanks

**Comment by tjhei** [comment]
> OK. That makes sense. Thanks

the mirror is online again so you might be able to install without any changes now (but still times out occasionally)

**Comment by stmcgovern** [comment]
Thanks, I already got things going as suggested before. I just reran the candi script now and the mirror works. I'm all set. And congratulations on your return to Clemson!
